name: 'Bump Chart Version'
description: 'Automatically Bump Helm Chart Version'
author: beehivewarrior
branding:
  icon: anchor
  color: blue

inputs:
  chart_name:
    description: 'Chart to be bumped'
    required: true
  bump_strategy:
    description: 'How the chart should be bumped'
    required: false
    default: 'PATCH'

outputs:
  version_bumped:
    description: Boolean indicating that the version was incremented.
    value: ${{ steps.bump.outputs.version_bumped }}

runs:
  using: composite

  steps:
    - uses: actions/checkout@v3
      if: github.actor != 'first-mate-bot'
      with:
        fetch-depth: '2'

    - name: 'Check if Chart Changed'
      if: github.actor != 'first-mate-bot'
      uses: tj-actions/changed-files@v23
      id: 'chart-changed'
      with:
        files: |
          ${{ inputs.chart_name }}

    - name: "Bump Chart Version"
      id: bump
      if: github.actor != 'first-mate-bot' && steps.chart-changed.outputs.any_modified == 'true'
      env:
        BUMP_STRATEGY: ${{ inputs.bump_strategy }}
        CHART_NAME: ${{ inputs.chart_name }}
      shell: bash
      run: |
        entrypoint="import sys;
        import subprocess;
        from pathlib import Path;
        MAIN_SCRIPT = Path(r'${GITHUB_ACTION_PATH}') / 'auto_bump' / 'main.py';
        proc = subprocess.run([sys.executable, str(MAIN_SCRIPT)]);
        sys.exit(proc.returncode)
        "
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo $entrypoint | python
          echo "::set-output name=version_bumped::true"
        else
          echo $entrypoint | python3
          echo "::set-output name=version_bumped::true"
        fi
        

    - name: "Check For Bump"
      id: review
      if: github.actor != 'first-mate-bot' && steps.chart-changed.outputs.any_modified == 'true'
      env:
        BUMP_STRATEGY: ${{ inputs.bump_strategy }}
        FIRST_MATE_OLD_VERSION: ${{ steps.bump.outputs.old_version }}
        FIRST_MATE_NEW_VERSION: ${{ steps.bump.outputs.new_version }}

      run: |
        FM_MESSAGE=`cat <<EOF
        Bumped Helm Chart Version From "$FIRST_MATE_OLD_VERSION" to "$FIRST_MATE_NEW_VERSION"

        Changes committed by "${{ github.actor }}" in commit: "${{ github.event.after }}" altered the Helm Chart.
        I updated the Chart.yaml file using the "$BUMP_STRATEGY" strategy.
        
        Signed-off-by: first-mate-bot[bot] <bot@firstmate.dev>
        EOF
        `
        if [[ `git status --porcelain` ]]; then
          git config --local user.name "first-mate-bot"
          git config --local user.email "bot@firstmate.dev"
          git add -A
          git commit -m "$FM_MESSAGE"
          git push
        fi

      shell: bash