name: Auto Approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: |
          (
            github.event.pull_request.user.login == 'dependabot[bot]' ||
            github.event.pull_request.user.login == 'dependabot' ||
            github.event.pull_request.user.login == 'dependabot-preview[bot]' ||
            github.event.pull_request.user.login == 'dependabot-preview' ||
            github.event.pull_request.user.login == 'github-actions[bot]' ||
            github.event.pull_request.user.login == 'beehivewarrior'
          )
            &&
          (
            github.actor == 'dependabot[bot]' ||
            github.actor == 'dependabot' ||
            github.actor == 'dependabot-preview[bot]' ||
            github.actor == 'dependabot-preview' ||
            github.actor == 'github-actions[bot]' ||
            github.actor == 'beehivewarrior'
          )